services:
  emr:
    image: flaskemr:latest
    container_name: emr-cont
    ports:
      - 8080:8080
    volumes:
      - /Users/sarmad/Dockers/emr-app:/usr/src/app:rw
    restart: unless-stopped

networks:
  default:
    name: macbook
    external: true
